import { Task } from './TaskTable';

export const rates: { key: keyof Task; value: number }[] = [
	{ key: "mgr", value: 215 },
	{ key: "sptl", value: 200 },
	{ key: "ptl", value: 165 },
	{ key: "ps", value: 125 },
	{ key: "coop", value: 70 },
];

export const defaultData: Task[] = [
	{
		id: 1,
		task: "Visionmarking",
		assumptions: "",
		mgr: null,
		sptl: null,
		ptl: null,
		ps: null,
		coop: null,
		totalHours: 0,
		totalDollars: 0,
	},
	{
		id: 2,
		task: "Study/Report",
		assumptions: "",
		mgr: null,
		sptl: null,
		ptl: null,
		ps: null,
		coop: null,
		totalHours: 0,
		totalDollars: 0,
	},
	{
		id: 3,
		task: "Site Visit",
		assumptions: "",
		mgr: null,
		sptl: null,
		ptl: null,
		ps: null,
		coop: null,
		totalHours: 0,
		totalDollars: 0,
	},
	{
		id: 4,
		task: "Client Meeting/Meeting Notes",
		assumptions: "",
		mgr: null,
		sptl: null,
		ptl: null,
		ps: null,
		coop: null,
		totalHours: 0,
		totalDollars: 0,
	},
	{
		id: 5,
		task: "Department Head",
		assumptions: "",
		mgr: null,
		sptl: null,
		ptl: 5,
		ps: null,
		coop: null,
		totalHours: 0,
		totalDollars: 0,
	},
	{
		id: 6,
		task: "Scope Definition",
		assumptions: "",
		mgr: null,
		sptl: null,
		ptl: 69,
		ps: null,
		coop: null,
		totalHours: 0,
		totalDollars: 0,
	},
];