export type TableCell = {
	project_num: number;
	dept: string;
	phase: number;
	header: boolean;
	data: boolean;
	explanation: boolean;
	grayedOut: boolean;
	rowSum: boolean;
	colSum: boolean;
	value: string | number | null;
	row: number;
	col: number;
	isEditable: boolean;
};

export const dbData: TableCell[] = [
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: "MGR",
		row: 0,
		col: 3,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: "SPTL",
		row: 0,
		col: 4,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: "PTL",
		row: 0,
		col: 5,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: "PS",
		row: 0,
		col: 6,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: "COOP",
		row: 0,
		col: 7,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: false,
		explanation: true,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: 215,
		row: 1,
		col: 3,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: false,
		explanation: true,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: 200,
		row: 1,
		col: 4,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: false,
		explanation: true,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: 165,
		row: 1,
		col: 5,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: false,
		explanation: true,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: 125,
		row: 1,
		col: 6,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: false,
		explanation: true,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: 70,
		row: 1,
		col: 7,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: "Item #",
		row: 2,
		col: 0,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: "Department Task",
		row: 2,
		col: 1,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: "Assumptions",
		row: 2,
		col: 2,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: true,
		rowSum: false,
		colSum: false,
		value: null,
		row: 2,
		col: 3,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: true,
		rowSum: false,
		colSum: false,
		value: null,
		row: 2,
		col: 4,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: true,
		rowSum: false,
		colSum: false,
		value: null,
		row: 2,
		col: 5,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: true,
		rowSum: false,
		colSum: false,
		value: 5,
		row: 2,
		col: 6,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: true,
		rowSum: false,
		colSum: false,
		value: 55,
		row: 2,
		col: 7,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: true,
		colSum: false,
		value: null,
		row: 2,
		col: 8,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: true,
		colSum: false,
		value: null,
		row: 2,
		col: 9,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 0,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 1,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 2,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 3,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 4,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 5,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 6,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: true,
		value: null,
		row: 3,
		col: 7,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 8,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: false,
		data: true,
		explanation: false,
		grayedOut: false,
		rowSum: false,
		colSum: false,
		value: null,
		row: 3,
		col: 9,
		isEditable: true,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: true,
		colSum: false,
		value: "Total Hours",
		row: 2,
		col: 8,
		isEditable: false,
	},
	{
		project_num: 11035,
		dept: "H",
		phase: 1,
		header: true,
		data: false,
		explanation: false,
		grayedOut: false,
		rowSum: true,
		colSum: false,
		value: "Total Dollars",
		row: 2,
		col: 9,
		isEditable: false,
	},
];
